### ISSUE TITLE
Want Smoooth Scrolling

### ISSUE THREAD

**Issue by charlesdarwinson21** [charlesdarwinson21/Sports-website#4]

**Comment by saadii00** [comment]
Can you please assign it to me? I would love to contribute to it.

**Comment by Laksh-Devloper** [comment]
I would love to work on it Gotta do it with Lenis , one of the great library for smooth scrolling , i have knowledge and willingly will work on it

**Comment by Laksh-Devloper** [comment]
``  // Lenis Smooth Scroll setup
  useEffect(() => {
    const lenis = new Lenis();
    const raf = (time) => {
      lenis.raf(time);
      requestAnimationFrame(raf);
    };
    requestAnimationFrame(raf);

    return () => lenis.destroy(); // Cleanup on unmount
  }, []);``
